# Generated by Django 4.2.2 on 2023-06-10 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='captions',
            new_name='caption',
        ),
    ]
